/**
 * Audit Trail — mock data and event recording.
 *
 * Records sensitive actions performed by staff members so programs can
 * demonstrate compliance and investigate access issues.
 *
 * Actions covered (per requirements):
 *  - injury_status_changed        (AC #2: records actor, timestamp, player, old, new)
 *  - readiness_override_created
 *  - private_note_accessed
 *  - dossier_published
 *  - parent_visibility_changed
 *  - assignment_created
 *  - user_invited
 *  - access_request_submitted     (generated by PermissionGate on deny+request)
 *  - access_request_approved
 *  - staff_role_changed
 *
 * AUDIT_EVENTS is module-level mutable — recordAuditEvent() appends at runtime.
 */

import type { StaffRole, PermissionAction } from "@/lib/permissions";

/* ─── Action types ────────────────────────────────────────────────────────── */

export type AuditAction =
  | "injury_status_changed"
  | "readiness_override_created"
  | "private_note_accessed"
  | "dossier_published"
  | "parent_visibility_changed"
  | "assignment_created"
  | "user_invited"
  | "access_request_submitted"
  | "access_request_approved"
  | "access_denied"
  | "staff_role_changed"
  | "player_profile_viewed";

export const AUDIT_ACTION_LABEL: Record<AuditAction, string> = {
  injury_status_changed:       "Injury status changed",
  readiness_override_created:  "Readiness override created",
  private_note_accessed:       "Private note accessed",
  dossier_published:           "Dossier published",
  parent_visibility_changed:   "Parent visibility changed",
  assignment_created:          "Assignment created",
  user_invited:                "User invited",
  access_request_submitted:    "Access request submitted",
  access_request_approved:     "Access request approved",
  access_denied:               "Access denied",
  staff_role_changed:          "Staff role changed",
  player_profile_viewed:       "Player profile viewed",
};

export const AUDIT_ACTION_SEVERITY: Record<AuditAction, "info" | "warning" | "critical"> = {
  injury_status_changed:       "warning",
  readiness_override_created:  "warning",
  private_note_accessed:       "critical",
  dossier_published:           "warning",
  parent_visibility_changed:   "warning",
  assignment_created:          "info",
  user_invited:                "warning",
  access_request_submitted:    "info",
  access_request_approved:     "warning",
  access_denied:               "critical",
  staff_role_changed:          "critical",
  player_profile_viewed:       "info",
};

/* ─── Event shape ─────────────────────────────────────────────────────────── */

export type AuditTargetType = "player" | "staff" | "dossier" | "note" | "assignment" | "system";

export interface AuditEvent {
  id: string;
  action: AuditAction;
  /** Who performed the action */
  actorId: string;
  actorName: string;
  actorRole: StaffRole;
  /** ISO timestamp */
  timestamp: string;
  programId?: string;
  /** What was acted upon */
  targetType?: AuditTargetType;
  targetId?: string;
  targetName?: string;
  /**
   * For state-change events — the value before the action.
   * Required for AC #2 (injury_status_changed).
   */
  oldValue?: string;
  /**
   * For state-change events — the value after the action.
   * Required for AC #2 (injury_status_changed).
   */
  newValue?: string;
  /** Free-form key/value pairs for extra context */
  metadata?: Record<string, string>;
  /** Populated for access_denied / access_request_submitted events */
  blockedAction?: PermissionAction;
  /** Synthetic flag — events generated by the system, not a human */
  systemGenerated?: boolean;
}

/* ─── Seeded events ───────────────────────────────────────────────────────── */

/**
 * Module-level mutable log. recordAuditEvent() appends here at runtime.
 * Pre-seeded with representative events for each action type.
 */
export const AUDIT_EVENTS: AuditEvent[] = [

  /* ── AC #2: Injury status changed by athletic trainer ─────────────────── */
  {
    id: "ae_001",
    action: "injury_status_changed",
    actorId: "staff_trainer_001",
    actorName: "Dr. Maria Santos",
    actorRole: "athletic_trainer",
    timestamp: "2026-05-17T09:15:00Z",
    programId: "prog_varsity",
    targetType: "player",
    targetId: "a_7",
    targetName: "Miles Thompson",
    oldValue: "available",
    newValue: "injured",                // AC #2: old + new values recorded ✓
    metadata: {
      restriction: "no_contact",
      estimatedReturn: "2026-05-24",
      diagnosisCode: "ankle_sprain_grade2",
      notes: "Grade 2 right ankle sprain sustained in practice 05/16.",
    },
  },
  {
    id: "ae_002",
    action: "injury_status_changed",
    actorId: "staff_trainer_001",
    actorName: "Dr. Maria Santos",
    actorRole: "athletic_trainer",
    timestamp: "2026-05-14T14:30:00Z",
    programId: "prog_varsity",
    targetType: "player",
    targetId: "a_9",
    targetName: "Darius Grant",
    oldValue: "limited",
    newValue: "available",
    metadata: {
      restriction: "none",
      clearedBy: "Dr. Santos",
      notes: "Hamstring strain resolved. Full clearance granted.",
    },
  },

  /* ── Readiness override ───────────────────────────────────────────────── */
  {
    id: "ae_003",
    action: "readiness_override_created",
    actorId: "staff_grant",
    actorName: "Coach Grant",
    actorRole: "head_coach",
    timestamp: "2026-05-16T07:45:00Z",
    programId: "prog_varsity",
    targetType: "player",
    targetId: "a_3",
    targetName: "DeAndre Johnson",
    oldValue: "yellow",
    newValue: "green_override",
    metadata: {
      reason: "Game-day exception — player confirmed ready verbally",
      approvedBy: "Head Coach Grant",
    },
  },

  /* ── Private note accessed ────────────────────────────────────────────── */
  {
    id: "ae_004",
    action: "private_note_accessed",
    actorId: "staff_grant",
    actorName: "Coach Grant",
    actorRole: "head_coach",
    timestamp: "2026-05-17T08:00:00Z",
    programId: "prog_varsity",
    targetType: "note",
    targetId: "note_a1_001",
    targetName: "Private note — Jalen Carter",
    metadata: { noteCategory: "behavioral", accessReason: "IDP review" },
  },

  /* ── Dossier published ─────────────────────────────────────────────────── */
  {
    id: "ae_005",
    action: "dossier_published",
    actorId: "staff_grant",
    actorName: "Coach Grant",
    actorRole: "head_coach",
    timestamp: "2026-05-10T12:00:00Z",
    programId: "prog_varsity",
    targetType: "dossier",
    targetId: "doss_jalen_carter",
    targetName: "Jalen Carter — Class of 2027",
    oldValue: "approved",
    newValue: "published",
    metadata: { publicSlug: "jalen-carter-2027", reviewedBy: "Sandra Carter (parent)" },
  },

  /* ── Parent visibility changed ────────────────────────────────────────── */
  {
    id: "ae_006",
    action: "parent_visibility_changed",
    actorId: "staff_grant",
    actorName: "Coach Grant",
    actorRole: "head_coach",
    timestamp: "2026-05-15T11:20:00Z",
    programId: "prog_varsity",
    targetType: "player",
    targetId: "a_3",
    targetName: "DeAndre Johnson",
    oldValue: "full_access",
    newValue: "restricted",
    metadata: {
      section: "development_notes",
      reason: "Sensitive content — family requested restriction",
    },
  },

  /* ── Assignment created ───────────────────────────────────────────────── */
  {
    id: "ae_007",
    action: "assignment_created",
    actorId: "staff_grant",
    actorName: "Coach Grant",
    actorRole: "head_coach",
    timestamp: "2026-05-16T16:00:00Z",
    programId: "prog_varsity",
    targetType: "assignment",
    targetId: "pa_7",
    targetName: "Scout Team — Run #5 Marcus Hill",
    metadata: {
      assignedTo: "Isaiah Moore (a_5)",
      dueDate: "2026-05-21",
      type: "scout_team",
    },
  },

  /* ── User invited ─────────────────────────────────────────────────────── */
  {
    id: "ae_008",
    action: "user_invited",
    actorId: "staff_grant",
    actorName: "Coach Grant",
    actorRole: "head_coach",
    timestamp: "2026-05-13T10:00:00Z",
    programId: "prog_varsity",
    targetType: "staff",
    targetId: "pending_trainer_001",
    targetName: "Dr. Maria Santos",
    metadata: {
      invitedRole: "athletic_trainer",
      email: "msantos@barnegat.edu",
      status: "accepted",
    },
  },

  /* ── Access denied (video coordinator → injury notes) ────────────────── */
  {
    id: "ae_009",
    action: "access_denied",
    actorId: "staff_video_001",
    actorName: "Tyler Reed",
    actorRole: "video_coordinator",
    timestamp: "2026-05-17T10:45:00Z",
    programId: "prog_varsity",
    targetType: "note",
    targetId: "injury_notes_section",
    targetName: "Injury Notes",
    blockedAction: "view_injury_notes",
    systemGenerated: true,
    metadata: { attemptedRoute: "/app/coach/players/a_7/injury" },
  },

  /* ── Staff role changed ───────────────────────────────────────────────── */
  {
    id: "ae_010",
    action: "staff_role_changed",
    actorId: "staff_grant",
    actorName: "Coach Grant",
    actorRole: "head_coach",
    timestamp: "2026-05-12T14:00:00Z",
    programId: "prog_varsity",
    targetType: "staff",
    targetId: "staff_martinez",
    targetName: "Coach Martinez",
    oldValue: "assistant_coach",
    newValue: "player_dev_coach",
    metadata: { reason: "Restructured coaching responsibilities for spring AAU season" },
  },

  /* ── Access request submitted ─────────────────────────────────────────── */
  {
    id: "ae_011",
    action: "access_request_submitted",
    actorId: "staff_video_001",
    actorName: "Tyler Reed",
    actorRole: "video_coordinator",
    timestamp: "2026-05-17T10:46:00Z",
    programId: "prog_varsity",
    targetType: "note",
    blockedAction: "view_injury_notes",
    metadata: { justification: "Need injury context to tag availability in film sessions" },
  },
];

/* ─── Counter for runtime-generated IDs ──────────────────────────────────── */

let _counter = AUDIT_EVENTS.length + 1;

/* ─── Record function ────────────────────────────────────────────────────── */

/**
 * Append a new audit event to the module-level log.
 * Call at the point of each sensitive action.
 *
 * AC #2: When an athletic trainer updates injury status, this records
 * actorId, actorName, actorRole, timestamp, targetId, targetName,
 * oldValue, and newValue.
 */
export function recordAuditEvent(
  event: Omit<AuditEvent, "id" | "timestamp">,
): AuditEvent {
  const full: AuditEvent = {
    ...event,
    id: `ae_${String(_counter++).padStart(3, "0")}`,
    timestamp: new Date().toISOString(),
  };
  AUDIT_EVENTS.push(full);
  return full;
}

/* ─── Query helpers ──────────────────────────────────────────────────────── */

export function getAuditEventsForPlayer(playerId: string): AuditEvent[] {
  return AUDIT_EVENTS.filter((e) => e.targetId === playerId);
}

export function getAuditEventsForActor(actorId: string): AuditEvent[] {
  return AUDIT_EVENTS.filter((e) => e.actorId === actorId);
}

export function getAuditEventsByAction(action: AuditAction): AuditEvent[] {
  return AUDIT_EVENTS.filter((e) => e.action === action);
}

export function getRecentAuditEvents(limit = 20): AuditEvent[] {
  return [...AUDIT_EVENTS]
    .sort((a, b) => b.timestamp.localeCompare(a.timestamp))
    .slice(0, limit);
}

/* ─── Mock staff roster for StaffRolesPage ──────────────────────────────── */

export interface StaffRecord {
  id: string;
  name: string;
  initials: string;
  email: string;
  staffRole: StaffRole;
  programIds: string[];
  joinedDate: string;
  lastActive: string;
  status: "active" | "pending" | "suspended";
  invitedBy?: string;
}

export const STAFF_RECORDS: StaffRecord[] = [
  {
    id: "staff_grant",
    name: "Coach Grant",
    initials: "CG",
    email: "grant@barnegat.edu",
    staffRole: "head_coach",
    programIds: ["prog_varsity", "prog_aau_17u"],
    joinedDate: "2020-08-15",
    lastActive: "2026-05-18T07:30:00Z",
    status: "active",
  },
  {
    id: "staff_martinez",
    name: "Coach Martinez",
    initials: "CM",
    email: "martinez@barnegat.edu",
    staffRole: "player_dev_coach",
    programIds: ["prog_varsity", "prog_jv"],
    joinedDate: "2021-09-01",
    lastActive: "2026-05-17T18:00:00Z",
    status: "active",
    invitedBy: "staff_grant",
  },
  {
    id: "staff_johnson_c",
    name: "Coach Johnson",
    initials: "CJ",
    email: "cjohnson@barnegat.edu",
    staffRole: "assistant_coach",
    programIds: ["prog_jv", "prog_freshman"],
    joinedDate: "2022-08-01",
    lastActive: "2026-05-16T17:00:00Z",
    status: "active",
    invitedBy: "staff_grant",
  },
  {
    id: "staff_trainer_001",
    name: "Dr. Maria Santos",
    initials: "MS",
    email: "msantos@barnegat.edu",
    staffRole: "athletic_trainer",
    programIds: ["prog_varsity", "prog_jv", "prog_freshman"],
    joinedDate: "2023-01-15",
    lastActive: "2026-05-18T09:20:00Z",
    status: "active",
    invitedBy: "staff_grant",
  },
  {
    id: "staff_video_001",
    name: "Tyler Reed",
    initials: "TR",
    email: "treed@barnegat.edu",
    staffRole: "video_coordinator",
    programIds: ["prog_varsity"],
    joinedDate: "2024-09-01",
    lastActive: "2026-05-17T10:45:00Z",
    status: "active",
    invitedBy: "staff_grant",
  },
  {
    id: "staff_strength_001",
    name: "Marcus Webb",
    initials: "MW",
    email: "mwebb@barnegat.edu",
    staffRole: "strength_coach",
    programIds: ["prog_varsity", "prog_aau_17u"],
    joinedDate: "2023-06-01",
    lastActive: "2026-05-17T07:00:00Z",
    status: "active",
    invitedBy: "staff_grant",
  },
  {
    id: "staff_ops_001",
    name: "Angela Kim",
    initials: "AK",
    email: "akim@barnegat.edu",
    staffRole: "director_of_ops",
    programIds: ["prog_varsity", "prog_jv", "prog_freshman", "prog_aau_17u"],
    joinedDate: "2021-06-01",
    lastActive: "2026-05-18T08:45:00Z",
    status: "active",
    invitedBy: "staff_grant",
  },
  {
    id: "staff_pending_001",
    name: "Devon Clarke",
    initials: "DC",
    email: "dclarke@barnegat.edu",
    staffRole: "assistant_coach",
    programIds: ["prog_varsity"],
    joinedDate: "2026-05-15",
    lastActive: "2026-05-15T12:00:00Z",
    status: "pending",
    invitedBy: "staff_grant",
  },
];

export function getStaffRecordById(id: string): StaffRecord | undefined {
  return STAFF_RECORDS.find((s) => s.id === id);
}
