-- Migration: 0017_compliance_tools
-- Adds the safety_incidents table for structured compliance reporting.
--
-- Design
-- ──────
-- safety_incidents is a first-class compliance record: any org member can
-- submit a formal incident report about a message, thread, user, or
-- athlete-welfare concern.  Unlike safety_flags (which are auto-generated by
-- the rule engine), incidents are human-authored and go through a review
-- workflow with an external-escalation path.
--
-- status lifecycle
-- ────────────────
--   open               Submitted, not yet reviewed
--   under_review       Admin has taken the item; investigation in progress
--   resolved           Closed internally; resolution_note required
--   escalated_external Reported to an external body (governing org, law enforcement)

CREATE TABLE IF NOT EXISTS safety_incidents (
  id                TEXT        PRIMARY KEY,
  org_id            TEXT        NOT NULL,
  -- The user who filed the report.
  reporter_id       TEXT        NOT NULL,
  reporter_role     TEXT        NOT NULL,
  -- What kind of object the report is about.
  subject_type      TEXT        NOT NULL,  -- message | thread | user | athlete_concern
  -- ID of the specific object, if applicable.
  subject_id        TEXT,
  -- Classification of the incident.
  category          TEXT        NOT NULL,  -- inappropriate_contact | policy_violation | grooming_concern | harassment | boundary_violation | other
  severity          TEXT        NOT NULL DEFAULT 'medium',
  -- Free-text narrative from the reporter.
  notes             TEXT        NOT NULL,
  -- Optional supporting evidence: snapshots, matched rules, attachments refs.
  evidence_snapshot JSONB       NOT NULL DEFAULT '{}',
  -- Review workflow status.
  status            TEXT        NOT NULL DEFAULT 'open',  -- open | under_review | resolved | escalated_external
  -- Clerk user ID of the admin who closed/resolved the incident.
  resolved_by       TEXT,
  resolution_note   TEXT,
  resolved_at       TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS safety_incidents_org_created_idx
  ON safety_incidents (org_id, created_at DESC);

CREATE INDEX IF NOT EXISTS safety_incidents_org_status_idx
  ON safety_incidents (org_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS safety_incidents_reporter_idx
  ON safety_incidents (reporter_id);

CREATE INDEX IF NOT EXISTS safety_incidents_subject_idx
  ON safety_incidents (subject_id)
  WHERE subject_id IS NOT NULL;
